### ISSUE TITLE
"file img.ado not found"

### ISSUE THREAD

**Issue by palpen** [haghish/Weaver#1]
Hi there,

First, this package is fantastic and I'm looking forward to making it a part of my workflow. I am, however, facing the following issue. I'm trying to run the following 

```
set more off

capture weave close
weave using weave_ex, replace date

cd "~/Desktop"

sysuse auto, clear

histogram price, title("Price histogram")
graph export price.png, replace
img using price.png, title("#_Figure 1_#. Histogram of the price variable")

weave close
```

but I am getting the `"file img.ado not found"` error. Any idea why this might be the case? I believe I have installed all the packages required. I am also using Stata 13.1 on OSX.

**Comment by haghish** [comment]
what is your weaver version? Did you install the latest version from GitHub?

**Comment by palpen** [comment]
In the Stata help file for weaver, it says Version 3.3.8

**Comment by haghish** [comment]
Please update it from GitHub. The current version is 3.4.0. It should work

https://github.com/haghish/weaver

**Comment by palpen** [comment]
Thank you!
